#!/bin/bash
pkill twinkle
pkill mousepad

#BLOQUEO DE TECLAS F

#TECLAS ALT Y CTRL (ENTRE EL ENTER Y LAS DEL TECLADO NUMERICO INICIO SUPR ETC)
#xmodmap -e 'keycode 37='
xmodmap -e 'keycode 64='
#xmodmap -e 'keycode 105='
xmodmap -e 'keycode 108'
xmodmap -e 'keycode 110'
xmodmap -e 'keycode 112'
xmodmap -e 'keycode 115'
xmodmap -e 'keycode 117'
xmodmap -e 'keycode 118'
xmodmap -e 'keycode 119'

#FLECHAS DE TECLADO
#xmodmap -e 'keycode 113='
#xmodmap -e 'keycode 114='

#TECLAS F
#xmodmap -e 'keycode 67='
#xmodmap -e 'keycode 68='
#xmodmap -e 'keycode 69='
#xmodmap -e 'keycode 70='
#xmodmap -e 'keycode 71='
#xmodmap -e 'keycode 72='
#xmodmap -e 'keycode 73='
#xmodmap -e 'keycode 74='
#xmodmap -e 'keycode 75='
#xmodmap -e 'keycode 76='
#xmodmap -e 'keycode 95='
#xmodmap -e 'keycode 96='


#TECLADO ALFANUMERICO
#xmodmap -e 'keycode 79='
#xmodmap -e 'keycode 80='
#xmodmap -e 'keycode 81='
#xmodmap -e 'keycode 82='
#xmodmap -e 'keycode 83='
#xmodmap -e 'keycode 84='
#xmodmap -e 'keycode 85='
#xmodmap -e 'keycode 86='
#xmodmap -e 'keycode 87='
#xmodmap -e 'keycode 88='
#xmodmap -e 'keycode 89='

#BLOQUEO DE MOUSE
#xmodmap -e 'pointer = 1 2 99'

#PONER EN HORA EL SISTEMA
ntpdate sit6.dialdata.com.ar

#DAMOS PERMISO DE RX A EL USUARIO
/bin/chmod -R u=rx $HOME/Escritorio


#BORRAMOS DIRECTORIO DE TWINKLE EN CASO DE QUE EXISTA
/bin/rm -rf $HOME/.twinkle


#CREAMOS EL DIRECTORIO DE TWINKLE
/bin/mkdir $HOME/.twinkle
/bin/mkdir $HOME/.twinkle/tmp

#CONSULTAR NUMERO DE INTERNO E IP Y GUARDARLO EN UNA VARIABLE
lynx=/usr/bin/lynx

ip=$(hostname -I) 
#$lynx -dump "http://sit6.dialdata.com.ar/http/scripts/login_sysop.php?ip=$ip&usuario=$USER"
#discador=$(lynx -dump "http://sit6.dialdata.com.ar/http/scripts/top.php?tipo=discador&nombreusuariosit=$USER")
discador=pbx1.tymdirect.com.ar


#interno=$(whiptail --inputbox "Escriba su interno de PBX1" 10 35 --nocancel 3>&1 1>&2 2>&3)
#password=$(whiptail --inputbox "Escriba su CLAVE DE PBX1" 10 35 --nocancel 3>&1 1>&2 2>&3)

#interno=$(lynx -dump "http://sit6.dialdata.com.ar/http/scripts/top.php?tipo=interno&nombreusuariosit=$USER")
#password=$(lynx -dump "http://sit6.dialdata.com.ar/http/scripts/top.php?tipo=password&nombreusuariosit=$USER")

# CFG PRINCIPAL
cd $HOME/.twinkle

#touch \ $interno".cfg"
#touch \ $interno".svc"
#touch \ "top.cfg"
#touch \ "top.svc"


echo "# USER
#user_name=$interno
user_name=
user_domain=$discador
#user_display=$interno
user_display=
user_organization=balat.com.ar
#auth_realm=$interno
auth_realm=
#auth_name=$interno
auth_name=
#auth_pass=$password
auth_pass=
auth_aka_op=00000000000000000000000000000000
auth_aka_amf=0000

# SIP SERVER
outbound_proxy=
all_requests_to_proxy=no
registrar=$discador
register_at_startup=yes
registration_time=3600
reg_add_qvalue=no
reg_qvalue=1

# RTP AUDIO
codecs=g711a,g711u
ptime=20
out_far_end_codec_pref=yes
in_far_end_codec_pref=yes
speex_nb_payload_type=97
speex_wb_payload_type=98
speex_uwb_payload_type=99
speex_bit_rate_type=cbr
speex_dtx=no
speex_penh=yes
speex_quality=6
speex_complexity=3
speex_dsp_vad=yes
speex_dsp_agc=yes
speex_dsp_aec=yes
speex_dsp_nrd=yes
speex_dsp_agc_level=20
ilbc_payload_type=96
ilbc_mode=30
g726_16_payload_type=102
g726_24_payload_type=103
g726_32_payload_type=104
g726_40_payload_type=105
g726_packing=rfc3551
dtmf_transport=auto
dtmf_payload_type=101
dtmf_duration=100
dtmf_pause=40
dtmf_volume=10

# SIP PROTOCOL
hold_variant=rfc3264
check_max_forwards=no
allow_missing_contact_reg=yes
registration_time_in_contact=yes
compact_headers=no
encode_multi_values_as_list=yes
use_domain_in_contact=no
allow_sdp_change=no
allow_redirection=yes
ask_user_to_redirect=yes
max_redirections=5
ext_100rel=supported
ext_replaces=yes
referee_hold=no
referrer_hold=yes
allow_refer=yes
ask_user_to_refer=yes
auto_refresh_refer_sub=no
attended_refer_to_aor=no
allow_xfer_consult_inprog=no
send_p_preferred_id=no

# Transport/NAT
sip_transport=auto
sip_transport_udp_threshold=1300
nat_public_ip=
stun_server=
persistent_tcp=yes
enable_nat_keepalive=no

# TIMERS
timer_noanswer=30
timer_nat_keepalive=30
timer_tcp_ping=30

# ADDRESS FORMAT
display_useronly_phone=yes
numerical_user_is_phone=no
remove_special_phone_symbols=yes
special_phone_symbols='-()/.'
use_tel_uri_for_phone=no

# RING TONES
ringtone_file=
ringback_file=

# SCRIPTS
script_incoming_call=
script_in_call_answered=
script_in_call_failed=
script_outgoing_call=
script_out_call_answered=
script_out_call_failed=
script_local_release=
script_remote_release=

# NUMBER CONVERSION

# SECURITY
zrtp_enabled=no
zrtp_goclear_warning=yes
zrtp_sdp=yes
zrtp_send_if_supported=no

# MWI
mwi_sollicited=no
mwi_user=
mwi_server=
mwi_via_proxy=no
mwi_subscription_time=3600
mwi_vm_address=

# INSTANT MESSAGE
im_max_sessions=10
im_send_iscomposing=yes

# PRESENCE
pres_subscription_time=3600
pres_publication_time=3600

pres_publish_startup=yes" >"top.cfg"


# TWINKLE SYS
echo "# AUDIO
dev_ringtone=alsa:default
dev_speaker=alsa:plughw:1,0
dev_mic=alsa:plughw:1,0
validate_audio_dev=no
alsa_play_period_size=128
alsa_capture_period_size=32
oss_fragment_size=128

# LOG 
log_max_size=5
log_show_sip=yes
log_show_stun=yes
log_show_memory=yes
log_show_debug=no

# GUI 
gui_use_systray=yes
gui_hide_on_close=yes
gui_auto_show_incoming=no
gui_auto_show_timeout=10
gui_browser_cmd=
gui_show_call_osd=no

# Address book
ab_show_sip_only=no
ab_lookup_name=yes
ab_override_display=yes
ab_lookup_photo=yes

# Call history
ch_max_size=50

# Services
call_waiting=yes
hangup_both_3way=yes

# Startup
start_user_profile=top
#start_hidden=yes
start_hidden=now

# Network
sip_port=5060
rtp_port=8000
sip_max_udp_size=65535
sip_max_tcp_size=1000000

# Ring tones
play_ringtone=yes
ringtone_file=
play_ringback=yes
ringback_file=

# MIME settings
mime_shared_database=/usr/share/mime/globs

# Persistent user interface state
last_used_profile=
redial_url=
redial_display=
redial_subject=
redial_profile=
redial_hide_user=no
show_display=yes
show_buddy_list=yes
warn_hide_user=yes

# UI session settings
ui_session_id=
ui_session_main_geometry=0,0,0,0
ui_session_main_hidden=no
ui_session_main_state=0" >twinkle.sys

#TWINKLE SVC

echo \ "dnd=no
auto_answer=no" >"top.svc"

echo " Pasos para configurar twinkle
1) Vaya al menu edit, user profile..
2) En Your name, user name y authentication name complete su usuario de pbx1
3) En password complete la password y ponga OK
4) En el menu registration, deregister y luego register
5) Finalmente en la ventana aparecera a la derecha -Registration Succeded-
6) Puede cerrar la ventana esta, el twinkle y abrir el navegador

Tips para uso de twinkle

1) Para loguearse a la cola marcando 0*55 y 0*56 se hace desde el campo Call: y luego se aprieta Dial
2) Atender los llamados usar Answer
3) Para cortar los llamados usar Bye" >"pasos.txt"


#INICIO DE TWINKLE
pkill twinkle
/usr/bin/twinkle &
sleep 1
/usr/bin/mousepad $HOME/.twinkle/pasos.txt &



